//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.225
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pms.Data.Integration.SkillManagementService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://ws.model.skillmanagement.app.pms.logica.com/", ConfigurationName="SkillManagementService.SkillManagementServiceEndpoint")]
    public interface SkillManagementServiceEndpoint {
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(response))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(request))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        Pms.Data.Integration.SkillManagementService.getAllCompetenciesResponse1 getAllCompetencies(Pms.Data.Integration.SkillManagementService.getAllCompetenciesRequest1 request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(response))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(request))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        Pms.Data.Integration.SkillManagementService.getAllCompetencyGroupsResponse1 getAllCompetencyGroups(Pms.Data.Integration.SkillManagementService.getAllCompetencyGroupsRequest1 request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(response))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(request))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        Pms.Data.Integration.SkillManagementService.getAllTechnologyKnowledgeDetailsResponse1 getAllTechnologyKnowledgeDetails(Pms.Data.Integration.SkillManagementService.getAllTechnologyKnowledgeDetailsRequest1 request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(response))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(request))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        Pms.Data.Integration.SkillManagementService.getAllTechnologyKnowledgeGroupsResponse1 getAllTechnologyKnowledgeGroups(Pms.Data.Integration.SkillManagementService.getAllTechnologyKnowledgeGroupsRequest1 request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(response))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(request))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        Pms.Data.Integration.SkillManagementService.getScoreCardResponse1 getScoreCard(Pms.Data.Integration.SkillManagementService.getScoreCardRequest1 request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(response))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(request))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        Pms.Data.Integration.SkillManagementService.saveScoreCardResponse1 saveScoreCard(Pms.Data.Integration.SkillManagementService.saveScoreCardRequest1 request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.225")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.model.skillmanagement.app.pms.logica.com/")]
    public partial class getAllCompetenciesRequest : genericRequest {
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(getAllTechnologyKnowledgeGroupsRequest))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(getAllTechnologyKnowledgeDetailsRequest))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(getAllCompetencyGroupsRequest))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(getScoreCardRequest))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(getAllCompetenciesRequest))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(saveScoreCardRequest))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.225")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.model.skillmanagement.app.pms.logica.com/")]
    public partial class genericRequest : request {
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(genericRequest))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(getAllTechnologyKnowledgeGroupsRequest))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(getAllTechnologyKnowledgeDetailsRequest))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(getAllCompetencyGroupsRequest))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(getScoreCardRequest))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(getAllCompetenciesRequest))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(saveScoreCardRequest))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.225")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.model.skillmanagement.app.pms.logica.com/")]
    public partial class request : object, System.ComponentModel.INotifyPropertyChanged {
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.225")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.model.skillmanagement.app.pms.logica.com/")]
    public partial class technologyKnowledgeGroupDto : object, System.ComponentModel.INotifyPropertyChanged {
        
        private long competencyGroupIdField;
        
        private bool competencyGroupIdFieldSpecified;
        
        private long competencyIdField;
        
        private bool competencyIdFieldSpecified;
        
        private string createByField;
        
        private System.DateTime createDateField;
        
        private bool createDateFieldSpecified;
        
        private string techField;
        
        private string technologyKnowledgeGroupDescriptionField;
        
        private long technologyKnowledgeGroupIdField;
        
        private bool technologyKnowledgeGroupIdFieldSpecified;
        
        private string technologyKnowledgeGroupNameField;
        
        private string updateByField;
        
        private System.DateTime updateDateField;
        
        private bool updateDateFieldSpecified;
        
        private string updateReasonField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public long competencyGroupId {
            get {
                return this.competencyGroupIdField;
            }
            set {
                this.competencyGroupIdField = value;
                this.RaisePropertyChanged("competencyGroupId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool competencyGroupIdSpecified {
            get {
                return this.competencyGroupIdFieldSpecified;
            }
            set {
                this.competencyGroupIdFieldSpecified = value;
                this.RaisePropertyChanged("competencyGroupIdSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public long competencyId {
            get {
                return this.competencyIdField;
            }
            set {
                this.competencyIdField = value;
                this.RaisePropertyChanged("competencyId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool competencyIdSpecified {
            get {
                return this.competencyIdFieldSpecified;
            }
            set {
                this.competencyIdFieldSpecified = value;
                this.RaisePropertyChanged("competencyIdSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string createBy {
            get {
                return this.createByField;
            }
            set {
                this.createByField = value;
                this.RaisePropertyChanged("createBy");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public System.DateTime createDate {
            get {
                return this.createDateField;
            }
            set {
                this.createDateField = value;
                this.RaisePropertyChanged("createDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool createDateSpecified {
            get {
                return this.createDateFieldSpecified;
            }
            set {
                this.createDateFieldSpecified = value;
                this.RaisePropertyChanged("createDateSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string tech {
            get {
                return this.techField;
            }
            set {
                this.techField = value;
                this.RaisePropertyChanged("tech");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string technologyKnowledgeGroupDescription {
            get {
                return this.technologyKnowledgeGroupDescriptionField;
            }
            set {
                this.technologyKnowledgeGroupDescriptionField = value;
                this.RaisePropertyChanged("technologyKnowledgeGroupDescription");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public long technologyKnowledgeGroupId {
            get {
                return this.technologyKnowledgeGroupIdField;
            }
            set {
                this.technologyKnowledgeGroupIdField = value;
                this.RaisePropertyChanged("technologyKnowledgeGroupId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool technologyKnowledgeGroupIdSpecified {
            get {
                return this.technologyKnowledgeGroupIdFieldSpecified;
            }
            set {
                this.technologyKnowledgeGroupIdFieldSpecified = value;
                this.RaisePropertyChanged("technologyKnowledgeGroupIdSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string technologyKnowledgeGroupName {
            get {
                return this.technologyKnowledgeGroupNameField;
            }
            set {
                this.technologyKnowledgeGroupNameField = value;
                this.RaisePropertyChanged("technologyKnowledgeGroupName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public string updateBy {
            get {
                return this.updateByField;
            }
            set {
                this.updateByField = value;
                this.RaisePropertyChanged("updateBy");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public System.DateTime updateDate {
            get {
                return this.updateDateField;
            }
            set {
                this.updateDateField = value;
                this.RaisePropertyChanged("updateDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool updateDateSpecified {
            get {
                return this.updateDateFieldSpecified;
            }
            set {
                this.updateDateFieldSpecified = value;
                this.RaisePropertyChanged("updateDateSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
        public string updateReason {
            get {
                return this.updateReasonField;
            }
            set {
                this.updateReasonField = value;
                this.RaisePropertyChanged("updateReason");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.225")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.model.skillmanagement.app.pms.logica.com/")]
    public partial class technologyKnowledgeDetailDto : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string createByField;
        
        private System.DateTime createDateField;
        
        private bool createDateFieldSpecified;
        
        private string technologyKnowledgeDetailDescriptionField;
        
        private long technologyKnowledgeDetailIdField;
        
        private bool technologyKnowledgeDetailIdFieldSpecified;
        
        private string technologyKnowledgeDetailNameField;
        
        private long technologyKnowledgeGroupIdField;
        
        private bool technologyKnowledgeGroupIdFieldSpecified;
        
        private string updateByField;
        
        private System.DateTime updateDateField;
        
        private bool updateDateFieldSpecified;
        
        private string updateReasonField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string createBy {
            get {
                return this.createByField;
            }
            set {
                this.createByField = value;
                this.RaisePropertyChanged("createBy");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public System.DateTime createDate {
            get {
                return this.createDateField;
            }
            set {
                this.createDateField = value;
                this.RaisePropertyChanged("createDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool createDateSpecified {
            get {
                return this.createDateFieldSpecified;
            }
            set {
                this.createDateFieldSpecified = value;
                this.RaisePropertyChanged("createDateSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string technologyKnowledgeDetailDescription {
            get {
                return this.technologyKnowledgeDetailDescriptionField;
            }
            set {
                this.technologyKnowledgeDetailDescriptionField = value;
                this.RaisePropertyChanged("technologyKnowledgeDetailDescription");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public long technologyKnowledgeDetailId {
            get {
                return this.technologyKnowledgeDetailIdField;
            }
            set {
                this.technologyKnowledgeDetailIdField = value;
                this.RaisePropertyChanged("technologyKnowledgeDetailId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool technologyKnowledgeDetailIdSpecified {
            get {
                return this.technologyKnowledgeDetailIdFieldSpecified;
            }
            set {
                this.technologyKnowledgeDetailIdFieldSpecified = value;
                this.RaisePropertyChanged("technologyKnowledgeDetailIdSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string technologyKnowledgeDetailName {
            get {
                return this.technologyKnowledgeDetailNameField;
            }
            set {
                this.technologyKnowledgeDetailNameField = value;
                this.RaisePropertyChanged("technologyKnowledgeDetailName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public long technologyKnowledgeGroupId {
            get {
                return this.technologyKnowledgeGroupIdField;
            }
            set {
                this.technologyKnowledgeGroupIdField = value;
                this.RaisePropertyChanged("technologyKnowledgeGroupId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool technologyKnowledgeGroupIdSpecified {
            get {
                return this.technologyKnowledgeGroupIdFieldSpecified;
            }
            set {
                this.technologyKnowledgeGroupIdFieldSpecified = value;
                this.RaisePropertyChanged("technologyKnowledgeGroupIdSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string updateBy {
            get {
                return this.updateByField;
            }
            set {
                this.updateByField = value;
                this.RaisePropertyChanged("updateBy");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public System.DateTime updateDate {
            get {
                return this.updateDateField;
            }
            set {
                this.updateDateField = value;
                this.RaisePropertyChanged("updateDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool updateDateSpecified {
            get {
                return this.updateDateFieldSpecified;
            }
            set {
                this.updateDateFieldSpecified = value;
                this.RaisePropertyChanged("updateDateSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public string updateReason {
            get {
                return this.updateReasonField;
            }
            set {
                this.updateReasonField = value;
                this.RaisePropertyChanged("updateReason");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.225")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.model.skillmanagement.app.pms.logica.com/")]
    public partial class competencyGroupDto : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string competencyGroupDescriptionField;
        
        private long competencyGroupIdField;
        
        private bool competencyGroupIdFieldSpecified;
        
        private string competencyGroupNameField;
        
        private long competencyIdField;
        
        private bool competencyIdFieldSpecified;
        
        private string createByField;
        
        private System.DateTime createDateField;
        
        private bool createDateFieldSpecified;
        
        private string updateByField;
        
        private System.DateTime updateDateField;
        
        private bool updateDateFieldSpecified;
        
        private string updateReasonField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string competencyGroupDescription {
            get {
                return this.competencyGroupDescriptionField;
            }
            set {
                this.competencyGroupDescriptionField = value;
                this.RaisePropertyChanged("competencyGroupDescription");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public long competencyGroupId {
            get {
                return this.competencyGroupIdField;
            }
            set {
                this.competencyGroupIdField = value;
                this.RaisePropertyChanged("competencyGroupId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool competencyGroupIdSpecified {
            get {
                return this.competencyGroupIdFieldSpecified;
            }
            set {
                this.competencyGroupIdFieldSpecified = value;
                this.RaisePropertyChanged("competencyGroupIdSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string competencyGroupName {
            get {
                return this.competencyGroupNameField;
            }
            set {
                this.competencyGroupNameField = value;
                this.RaisePropertyChanged("competencyGroupName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public long competencyId {
            get {
                return this.competencyIdField;
            }
            set {
                this.competencyIdField = value;
                this.RaisePropertyChanged("competencyId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool competencyIdSpecified {
            get {
                return this.competencyIdFieldSpecified;
            }
            set {
                this.competencyIdFieldSpecified = value;
                this.RaisePropertyChanged("competencyIdSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string createBy {
            get {
                return this.createByField;
            }
            set {
                this.createByField = value;
                this.RaisePropertyChanged("createBy");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public System.DateTime createDate {
            get {
                return this.createDateField;
            }
            set {
                this.createDateField = value;
                this.RaisePropertyChanged("createDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool createDateSpecified {
            get {
                return this.createDateFieldSpecified;
            }
            set {
                this.createDateFieldSpecified = value;
                this.RaisePropertyChanged("createDateSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string updateBy {
            get {
                return this.updateByField;
            }
            set {
                this.updateByField = value;
                this.RaisePropertyChanged("updateBy");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public System.DateTime updateDate {
            get {
                return this.updateDateField;
            }
            set {
                this.updateDateField = value;
                this.RaisePropertyChanged("updateDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool updateDateSpecified {
            get {
                return this.updateDateFieldSpecified;
            }
            set {
                this.updateDateFieldSpecified = value;
                this.RaisePropertyChanged("updateDateSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public string updateReason {
            get {
                return this.updateReasonField;
            }
            set {
                this.updateReasonField = value;
                this.RaisePropertyChanged("updateReason");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.225")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.model.skillmanagement.app.pms.logica.com/")]
    public partial class scoreCardViewDto : object, System.ComponentModel.INotifyPropertyChanged {
        
        private long competencyGroupIdField;
        
        private bool competencyGroupIdFieldSpecified;
        
        private long competencyIdField;
        
        private bool competencyIdFieldSpecified;
        
        private string competencyNameField;
        
        private long employeeIdField;
        
        private bool employeeIdFieldSpecified;
        
        private string firstNameField;
        
        private string lastNameField;
        
        private long personIdField;
        
        private bool personIdFieldSpecified;
        
        private int scoreLevelField;
        
        private bool scoreLevelFieldSpecified;
        
        private long technologyKnowledgeDetailIdField;
        
        private bool technologyKnowledgeDetailIdFieldSpecified;
        
        private string technologyKnowledgeDetailNameField;
        
        private long technologyKnowledgeGroupIdField;
        
        private bool technologyKnowledgeGroupIdFieldSpecified;
        
        private string technologyKnowledgeGroupNameField;
        
        private int yearField;
        
        private bool yearFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public long competencyGroupId {
            get {
                return this.competencyGroupIdField;
            }
            set {
                this.competencyGroupIdField = value;
                this.RaisePropertyChanged("competencyGroupId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool competencyGroupIdSpecified {
            get {
                return this.competencyGroupIdFieldSpecified;
            }
            set {
                this.competencyGroupIdFieldSpecified = value;
                this.RaisePropertyChanged("competencyGroupIdSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public long competencyId {
            get {
                return this.competencyIdField;
            }
            set {
                this.competencyIdField = value;
                this.RaisePropertyChanged("competencyId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool competencyIdSpecified {
            get {
                return this.competencyIdFieldSpecified;
            }
            set {
                this.competencyIdFieldSpecified = value;
                this.RaisePropertyChanged("competencyIdSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string competencyName {
            get {
                return this.competencyNameField;
            }
            set {
                this.competencyNameField = value;
                this.RaisePropertyChanged("competencyName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public long employeeId {
            get {
                return this.employeeIdField;
            }
            set {
                this.employeeIdField = value;
                this.RaisePropertyChanged("employeeId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool employeeIdSpecified {
            get {
                return this.employeeIdFieldSpecified;
            }
            set {
                this.employeeIdFieldSpecified = value;
                this.RaisePropertyChanged("employeeIdSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string firstName {
            get {
                return this.firstNameField;
            }
            set {
                this.firstNameField = value;
                this.RaisePropertyChanged("firstName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string lastName {
            get {
                return this.lastNameField;
            }
            set {
                this.lastNameField = value;
                this.RaisePropertyChanged("lastName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public long personId {
            get {
                return this.personIdField;
            }
            set {
                this.personIdField = value;
                this.RaisePropertyChanged("personId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool personIdSpecified {
            get {
                return this.personIdFieldSpecified;
            }
            set {
                this.personIdFieldSpecified = value;
                this.RaisePropertyChanged("personIdSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public int scoreLevel {
            get {
                return this.scoreLevelField;
            }
            set {
                this.scoreLevelField = value;
                this.RaisePropertyChanged("scoreLevel");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool scoreLevelSpecified {
            get {
                return this.scoreLevelFieldSpecified;
            }
            set {
                this.scoreLevelFieldSpecified = value;
                this.RaisePropertyChanged("scoreLevelSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public long technologyKnowledgeDetailId {
            get {
                return this.technologyKnowledgeDetailIdField;
            }
            set {
                this.technologyKnowledgeDetailIdField = value;
                this.RaisePropertyChanged("technologyKnowledgeDetailId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool technologyKnowledgeDetailIdSpecified {
            get {
                return this.technologyKnowledgeDetailIdFieldSpecified;
            }
            set {
                this.technologyKnowledgeDetailIdFieldSpecified = value;
                this.RaisePropertyChanged("technologyKnowledgeDetailIdSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public string technologyKnowledgeDetailName {
            get {
                return this.technologyKnowledgeDetailNameField;
            }
            set {
                this.technologyKnowledgeDetailNameField = value;
                this.RaisePropertyChanged("technologyKnowledgeDetailName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
        public long technologyKnowledgeGroupId {
            get {
                return this.technologyKnowledgeGroupIdField;
            }
            set {
                this.technologyKnowledgeGroupIdField = value;
                this.RaisePropertyChanged("technologyKnowledgeGroupId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool technologyKnowledgeGroupIdSpecified {
            get {
                return this.technologyKnowledgeGroupIdFieldSpecified;
            }
            set {
                this.technologyKnowledgeGroupIdFieldSpecified = value;
                this.RaisePropertyChanged("technologyKnowledgeGroupIdSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=11)]
        public string technologyKnowledgeGroupName {
            get {
                return this.technologyKnowledgeGroupNameField;
            }
            set {
                this.technologyKnowledgeGroupNameField = value;
                this.RaisePropertyChanged("technologyKnowledgeGroupName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=12)]
        public int year {
            get {
                return this.yearField;
            }
            set {
                this.yearField = value;
                this.RaisePropertyChanged("year");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool yearSpecified {
            get {
                return this.yearFieldSpecified;
            }
            set {
                this.yearFieldSpecified = value;
                this.RaisePropertyChanged("yearSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.225")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.model.skillmanagement.app.pms.logica.com/")]
    public partial class competencyDto : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string comeptencyDescriptionField;
        
        private long comeptencyIdField;
        
        private bool comeptencyIdFieldSpecified;
        
        private string comeptencyNameField;
        
        private long competencyManagerIdField;
        
        private bool competencyManagerIdFieldSpecified;
        
        private string createByField;
        
        private System.DateTime createDateField;
        
        private bool createDateFieldSpecified;
        
        private long recordStatusIdField;
        
        private bool recordStatusIdFieldSpecified;
        
        private string updateByField;
        
        private System.DateTime updateDateField;
        
        private bool updateDateFieldSpecified;
        
        private string updateReasonField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string comeptencyDescription {
            get {
                return this.comeptencyDescriptionField;
            }
            set {
                this.comeptencyDescriptionField = value;
                this.RaisePropertyChanged("comeptencyDescription");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public long comeptencyId {
            get {
                return this.comeptencyIdField;
            }
            set {
                this.comeptencyIdField = value;
                this.RaisePropertyChanged("comeptencyId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool comeptencyIdSpecified {
            get {
                return this.comeptencyIdFieldSpecified;
            }
            set {
                this.comeptencyIdFieldSpecified = value;
                this.RaisePropertyChanged("comeptencyIdSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string comeptencyName {
            get {
                return this.comeptencyNameField;
            }
            set {
                this.comeptencyNameField = value;
                this.RaisePropertyChanged("comeptencyName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public long competencyManagerId {
            get {
                return this.competencyManagerIdField;
            }
            set {
                this.competencyManagerIdField = value;
                this.RaisePropertyChanged("competencyManagerId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool competencyManagerIdSpecified {
            get {
                return this.competencyManagerIdFieldSpecified;
            }
            set {
                this.competencyManagerIdFieldSpecified = value;
                this.RaisePropertyChanged("competencyManagerIdSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string createBy {
            get {
                return this.createByField;
            }
            set {
                this.createByField = value;
                this.RaisePropertyChanged("createBy");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public System.DateTime createDate {
            get {
                return this.createDateField;
            }
            set {
                this.createDateField = value;
                this.RaisePropertyChanged("createDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool createDateSpecified {
            get {
                return this.createDateFieldSpecified;
            }
            set {
                this.createDateFieldSpecified = value;
                this.RaisePropertyChanged("createDateSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public long recordStatusId {
            get {
                return this.recordStatusIdField;
            }
            set {
                this.recordStatusIdField = value;
                this.RaisePropertyChanged("recordStatusId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool recordStatusIdSpecified {
            get {
                return this.recordStatusIdFieldSpecified;
            }
            set {
                this.recordStatusIdFieldSpecified = value;
                this.RaisePropertyChanged("recordStatusIdSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string updateBy {
            get {
                return this.updateByField;
            }
            set {
                this.updateByField = value;
                this.RaisePropertyChanged("updateBy");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public System.DateTime updateDate {
            get {
                return this.updateDateField;
            }
            set {
                this.updateDateField = value;
                this.RaisePropertyChanged("updateDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool updateDateSpecified {
            get {
                return this.updateDateFieldSpecified;
            }
            set {
                this.updateDateFieldSpecified = value;
                this.RaisePropertyChanged("updateDateSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public string updateReason {
            get {
                return this.updateReasonField;
            }
            set {
                this.updateReasonField = value;
                this.RaisePropertyChanged("updateReason");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.225")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.model.skillmanagement.app.pms.logica.com/")]
    public partial class codeMessage : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int codeField;
        
        private string messageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
                this.RaisePropertyChanged("code");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
                this.RaisePropertyChanged("message");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(genericResponse))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(GetAllTechnologyKnowledgeGroupsResponse))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(GetAllTechnologyKnowledgeDetailsResponse))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(GetAllCompetencyGroupsResponse))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(GetScoreCardResponse))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(GetAllCompetenciesResponse))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(SaveScoreCardResponse))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.225")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.model.skillmanagement.app.pms.logica.com/")]
    public partial class response : object, System.ComponentModel.INotifyPropertyChanged {
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(GetAllTechnologyKnowledgeGroupsResponse))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(GetAllTechnologyKnowledgeDetailsResponse))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(GetAllCompetencyGroupsResponse))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(GetScoreCardResponse))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(GetAllCompetenciesResponse))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(SaveScoreCardResponse))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.225")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.model.skillmanagement.app.pms.logica.com/")]
    public partial class genericResponse : response {
        
        private codeMessage[] codeMessagesField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("codeMessages", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public codeMessage[] codeMessages {
            get {
                return this.codeMessagesField;
            }
            set {
                this.codeMessagesField = value;
                this.RaisePropertyChanged("codeMessages");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.225")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.model.skillmanagement.app.pms.logica.com/")]
    public partial class GetAllTechnologyKnowledgeGroupsResponse : genericResponse {
        
        private technologyKnowledgeGroupDto[] technologyKnowledgeGroupsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("technologyKnowledgeGroups", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public technologyKnowledgeGroupDto[] technologyKnowledgeGroups {
            get {
                return this.technologyKnowledgeGroupsField;
            }
            set {
                this.technologyKnowledgeGroupsField = value;
                this.RaisePropertyChanged("technologyKnowledgeGroups");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.225")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.model.skillmanagement.app.pms.logica.com/")]
    public partial class GetAllTechnologyKnowledgeDetailsResponse : genericResponse {
        
        private technologyKnowledgeDetailDto[] technologyKnowledgeDetailsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("technologyKnowledgeDetails", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public technologyKnowledgeDetailDto[] technologyKnowledgeDetails {
            get {
                return this.technologyKnowledgeDetailsField;
            }
            set {
                this.technologyKnowledgeDetailsField = value;
                this.RaisePropertyChanged("technologyKnowledgeDetails");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.225")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.model.skillmanagement.app.pms.logica.com/")]
    public partial class GetAllCompetencyGroupsResponse : genericResponse {
        
        private competencyGroupDto[] comptencyGroupsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("comptencyGroups", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public competencyGroupDto[] comptencyGroups {
            get {
                return this.comptencyGroupsField;
            }
            set {
                this.comptencyGroupsField = value;
                this.RaisePropertyChanged("comptencyGroups");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.225")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.model.skillmanagement.app.pms.logica.com/")]
    public partial class GetScoreCardResponse : genericResponse {
        
        private scoreCardViewDto[] scoreCardsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("scoreCards", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public scoreCardViewDto[] scoreCards {
            get {
                return this.scoreCardsField;
            }
            set {
                this.scoreCardsField = value;
                this.RaisePropertyChanged("scoreCards");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.225")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.model.skillmanagement.app.pms.logica.com/")]
    public partial class GetAllCompetenciesResponse : genericResponse {
        
        private competencyDto[] comptenciesField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("comptencies", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public competencyDto[] comptencies {
            get {
                return this.comptenciesField;
            }
            set {
                this.comptenciesField = value;
                this.RaisePropertyChanged("comptencies");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.225")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.model.skillmanagement.app.pms.logica.com/")]
    public partial class SaveScoreCardResponse : genericResponse {
        
        private string messageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
                this.RaisePropertyChanged("message");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.225")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.model.skillmanagement.app.pms.logica.com/")]
    public partial class scoreCardDto : object, System.ComponentModel.INotifyPropertyChanged {
        
        private long competencyGroupIdField;
        
        private bool competencyGroupIdFieldSpecified;
        
        private long competencyIdField;
        
        private bool competencyIdFieldSpecified;
        
        private long employeeIdField;
        
        private bool employeeIdFieldSpecified;
        
        private long personIdField;
        
        private bool personIdFieldSpecified;
        
        private long recordStatusIdField;
        
        private bool recordStatusIdFieldSpecified;
        
        private int scoreLevelField;
        
        private bool scoreLevelFieldSpecified;
        
        private long technologyKnowledgeGroupIdField;
        
        private bool technologyKnowledgeGroupIdFieldSpecified;
        
        private long technologyKnowlegeDetailIdField;
        
        private bool technologyKnowlegeDetailIdFieldSpecified;
        
        private string updateReasonField;
        
        private int yearField;
        
        private bool yearFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public long competencyGroupId {
            get {
                return this.competencyGroupIdField;
            }
            set {
                this.competencyGroupIdField = value;
                this.RaisePropertyChanged("competencyGroupId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool competencyGroupIdSpecified {
            get {
                return this.competencyGroupIdFieldSpecified;
            }
            set {
                this.competencyGroupIdFieldSpecified = value;
                this.RaisePropertyChanged("competencyGroupIdSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public long competencyId {
            get {
                return this.competencyIdField;
            }
            set {
                this.competencyIdField = value;
                this.RaisePropertyChanged("competencyId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool competencyIdSpecified {
            get {
                return this.competencyIdFieldSpecified;
            }
            set {
                this.competencyIdFieldSpecified = value;
                this.RaisePropertyChanged("competencyIdSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public long employeeId {
            get {
                return this.employeeIdField;
            }
            set {
                this.employeeIdField = value;
                this.RaisePropertyChanged("employeeId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool employeeIdSpecified {
            get {
                return this.employeeIdFieldSpecified;
            }
            set {
                this.employeeIdFieldSpecified = value;
                this.RaisePropertyChanged("employeeIdSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public long personId {
            get {
                return this.personIdField;
            }
            set {
                this.personIdField = value;
                this.RaisePropertyChanged("personId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool personIdSpecified {
            get {
                return this.personIdFieldSpecified;
            }
            set {
                this.personIdFieldSpecified = value;
                this.RaisePropertyChanged("personIdSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public long recordStatusId {
            get {
                return this.recordStatusIdField;
            }
            set {
                this.recordStatusIdField = value;
                this.RaisePropertyChanged("recordStatusId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool recordStatusIdSpecified {
            get {
                return this.recordStatusIdFieldSpecified;
            }
            set {
                this.recordStatusIdFieldSpecified = value;
                this.RaisePropertyChanged("recordStatusIdSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public int scoreLevel {
            get {
                return this.scoreLevelField;
            }
            set {
                this.scoreLevelField = value;
                this.RaisePropertyChanged("scoreLevel");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool scoreLevelSpecified {
            get {
                return this.scoreLevelFieldSpecified;
            }
            set {
                this.scoreLevelFieldSpecified = value;
                this.RaisePropertyChanged("scoreLevelSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public long technologyKnowledgeGroupId {
            get {
                return this.technologyKnowledgeGroupIdField;
            }
            set {
                this.technologyKnowledgeGroupIdField = value;
                this.RaisePropertyChanged("technologyKnowledgeGroupId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool technologyKnowledgeGroupIdSpecified {
            get {
                return this.technologyKnowledgeGroupIdFieldSpecified;
            }
            set {
                this.technologyKnowledgeGroupIdFieldSpecified = value;
                this.RaisePropertyChanged("technologyKnowledgeGroupIdSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public long technologyKnowlegeDetailId {
            get {
                return this.technologyKnowlegeDetailIdField;
            }
            set {
                this.technologyKnowlegeDetailIdField = value;
                this.RaisePropertyChanged("technologyKnowlegeDetailId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool technologyKnowlegeDetailIdSpecified {
            get {
                return this.technologyKnowlegeDetailIdFieldSpecified;
            }
            set {
                this.technologyKnowlegeDetailIdFieldSpecified = value;
                this.RaisePropertyChanged("technologyKnowlegeDetailIdSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public string updateReason {
            get {
                return this.updateReasonField;
            }
            set {
                this.updateReasonField = value;
                this.RaisePropertyChanged("updateReason");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public int year {
            get {
                return this.yearField;
            }
            set {
                this.yearField = value;
                this.RaisePropertyChanged("year");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool yearSpecified {
            get {
                return this.yearFieldSpecified;
            }
            set {
                this.yearFieldSpecified = value;
                this.RaisePropertyChanged("yearSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.225")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.model.skillmanagement.app.pms.logica.com/")]
    public partial class getAllTechnologyKnowledgeGroupsRequest : genericRequest {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.225")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.model.skillmanagement.app.pms.logica.com/")]
    public partial class getAllTechnologyKnowledgeDetailsRequest : genericRequest {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.225")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.model.skillmanagement.app.pms.logica.com/")]
    public partial class getAllCompetencyGroupsRequest : genericRequest {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.225")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.model.skillmanagement.app.pms.logica.com/")]
    public partial class getScoreCardRequest : genericRequest {
        
        private long employeeIdField;
        
        private long competencyIdField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public long employeeId {
            get {
                return this.employeeIdField;
            }
            set {
                this.employeeIdField = value;
                this.RaisePropertyChanged("employeeId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public long competencyId {
            get {
                return this.competencyIdField;
            }
            set {
                this.competencyIdField = value;
                this.RaisePropertyChanged("competencyId");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.225")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.model.skillmanagement.app.pms.logica.com/")]
    public partial class saveScoreCardRequest : genericRequest {
        
        private scoreCardDto[] scoreCardsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("scoreCards", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public scoreCardDto[] scoreCards {
            get {
                return this.scoreCardsField;
            }
            set {
                this.scoreCardsField = value;
                this.RaisePropertyChanged("scoreCards");
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getAllCompetencies", WrapperNamespace="http://ws.model.skillmanagement.app.pms.logica.com/", IsWrapped=true)]
    public partial class getAllCompetenciesRequest1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.model.skillmanagement.app.pms.logica.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Pms.Data.Integration.SkillManagementService.getAllCompetenciesRequest arg0;
        
        public getAllCompetenciesRequest1() {
        }
        
        public getAllCompetenciesRequest1(Pms.Data.Integration.SkillManagementService.getAllCompetenciesRequest arg0) {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getAllCompetenciesResponse", WrapperNamespace="http://ws.model.skillmanagement.app.pms.logica.com/", IsWrapped=true)]
    public partial class getAllCompetenciesResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.model.skillmanagement.app.pms.logica.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Pms.Data.Integration.SkillManagementService.GetAllCompetenciesResponse @return;
        
        public getAllCompetenciesResponse1() {
        }
        
        public getAllCompetenciesResponse1(Pms.Data.Integration.SkillManagementService.GetAllCompetenciesResponse @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getAllCompetencyGroups", WrapperNamespace="http://ws.model.skillmanagement.app.pms.logica.com/", IsWrapped=true)]
    public partial class getAllCompetencyGroupsRequest1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.model.skillmanagement.app.pms.logica.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Pms.Data.Integration.SkillManagementService.getAllCompetencyGroupsRequest arg0;
        
        public getAllCompetencyGroupsRequest1() {
        }
        
        public getAllCompetencyGroupsRequest1(Pms.Data.Integration.SkillManagementService.getAllCompetencyGroupsRequest arg0) {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getAllCompetencyGroupsResponse", WrapperNamespace="http://ws.model.skillmanagement.app.pms.logica.com/", IsWrapped=true)]
    public partial class getAllCompetencyGroupsResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.model.skillmanagement.app.pms.logica.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Pms.Data.Integration.SkillManagementService.GetAllCompetencyGroupsResponse @return;
        
        public getAllCompetencyGroupsResponse1() {
        }
        
        public getAllCompetencyGroupsResponse1(Pms.Data.Integration.SkillManagementService.GetAllCompetencyGroupsResponse @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getAllTechnologyKnowledgeDetails", WrapperNamespace="http://ws.model.skillmanagement.app.pms.logica.com/", IsWrapped=true)]
    public partial class getAllTechnologyKnowledgeDetailsRequest1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.model.skillmanagement.app.pms.logica.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Pms.Data.Integration.SkillManagementService.getAllTechnologyKnowledgeDetailsRequest arg0;
        
        public getAllTechnologyKnowledgeDetailsRequest1() {
        }
        
        public getAllTechnologyKnowledgeDetailsRequest1(Pms.Data.Integration.SkillManagementService.getAllTechnologyKnowledgeDetailsRequest arg0) {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getAllTechnologyKnowledgeDetailsResponse", WrapperNamespace="http://ws.model.skillmanagement.app.pms.logica.com/", IsWrapped=true)]
    public partial class getAllTechnologyKnowledgeDetailsResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.model.skillmanagement.app.pms.logica.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Pms.Data.Integration.SkillManagementService.GetAllTechnologyKnowledgeDetailsResponse @return;
        
        public getAllTechnologyKnowledgeDetailsResponse1() {
        }
        
        public getAllTechnologyKnowledgeDetailsResponse1(Pms.Data.Integration.SkillManagementService.GetAllTechnologyKnowledgeDetailsResponse @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getAllTechnologyKnowledgeGroups", WrapperNamespace="http://ws.model.skillmanagement.app.pms.logica.com/", IsWrapped=true)]
    public partial class getAllTechnologyKnowledgeGroupsRequest1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.model.skillmanagement.app.pms.logica.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Pms.Data.Integration.SkillManagementService.getAllTechnologyKnowledgeGroupsRequest arg0;
        
        public getAllTechnologyKnowledgeGroupsRequest1() {
        }
        
        public getAllTechnologyKnowledgeGroupsRequest1(Pms.Data.Integration.SkillManagementService.getAllTechnologyKnowledgeGroupsRequest arg0) {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getAllTechnologyKnowledgeGroupsResponse", WrapperNamespace="http://ws.model.skillmanagement.app.pms.logica.com/", IsWrapped=true)]
    public partial class getAllTechnologyKnowledgeGroupsResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.model.skillmanagement.app.pms.logica.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Pms.Data.Integration.SkillManagementService.GetAllTechnologyKnowledgeGroupsResponse @return;
        
        public getAllTechnologyKnowledgeGroupsResponse1() {
        }
        
        public getAllTechnologyKnowledgeGroupsResponse1(Pms.Data.Integration.SkillManagementService.GetAllTechnologyKnowledgeGroupsResponse @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getScoreCard", WrapperNamespace="http://ws.model.skillmanagement.app.pms.logica.com/", IsWrapped=true)]
    public partial class getScoreCardRequest1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.model.skillmanagement.app.pms.logica.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Pms.Data.Integration.SkillManagementService.getScoreCardRequest arg0;
        
        public getScoreCardRequest1() {
        }
        
        public getScoreCardRequest1(Pms.Data.Integration.SkillManagementService.getScoreCardRequest arg0) {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getScoreCardResponse", WrapperNamespace="http://ws.model.skillmanagement.app.pms.logica.com/", IsWrapped=true)]
    public partial class getScoreCardResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.model.skillmanagement.app.pms.logica.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Pms.Data.Integration.SkillManagementService.GetScoreCardResponse @return;
        
        public getScoreCardResponse1() {
        }
        
        public getScoreCardResponse1(Pms.Data.Integration.SkillManagementService.GetScoreCardResponse @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="saveScoreCard", WrapperNamespace="http://ws.model.skillmanagement.app.pms.logica.com/", IsWrapped=true)]
    public partial class saveScoreCardRequest1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.model.skillmanagement.app.pms.logica.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Pms.Data.Integration.SkillManagementService.saveScoreCardRequest arg0;
        
        public saveScoreCardRequest1() {
        }
        
        public saveScoreCardRequest1(Pms.Data.Integration.SkillManagementService.saveScoreCardRequest arg0) {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="saveScoreCardResponse", WrapperNamespace="http://ws.model.skillmanagement.app.pms.logica.com/", IsWrapped=true)]
    public partial class saveScoreCardResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.model.skillmanagement.app.pms.logica.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Pms.Data.Integration.SkillManagementService.SaveScoreCardResponse @return;
        
        public saveScoreCardResponse1() {
        }
        
        public saveScoreCardResponse1(Pms.Data.Integration.SkillManagementService.SaveScoreCardResponse @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface SkillManagementServiceEndpointChannel : Pms.Data.Integration.SkillManagementService.SkillManagementServiceEndpoint, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SkillManagementServiceEndpointClient : System.ServiceModel.ClientBase<Pms.Data.Integration.SkillManagementService.SkillManagementServiceEndpoint>, Pms.Data.Integration.SkillManagementService.SkillManagementServiceEndpoint {
        
        public SkillManagementServiceEndpointClient() {
        }
        
        public SkillManagementServiceEndpointClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SkillManagementServiceEndpointClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SkillManagementServiceEndpointClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SkillManagementServiceEndpointClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Pms.Data.Integration.SkillManagementService.getAllCompetenciesResponse1 Pms.Data.Integration.SkillManagementService.SkillManagementServiceEndpoint.getAllCompetencies(Pms.Data.Integration.SkillManagementService.getAllCompetenciesRequest1 request) {
            return base.Channel.getAllCompetencies(request);
        }
        
        public Pms.Data.Integration.SkillManagementService.GetAllCompetenciesResponse getAllCompetencies(Pms.Data.Integration.SkillManagementService.getAllCompetenciesRequest arg0) {
            Pms.Data.Integration.SkillManagementService.getAllCompetenciesRequest1 inValue = new Pms.Data.Integration.SkillManagementService.getAllCompetenciesRequest1();
            inValue.arg0 = arg0;
            Pms.Data.Integration.SkillManagementService.getAllCompetenciesResponse1 retVal = ((Pms.Data.Integration.SkillManagementService.SkillManagementServiceEndpoint)(this)).getAllCompetencies(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Pms.Data.Integration.SkillManagementService.getAllCompetencyGroupsResponse1 Pms.Data.Integration.SkillManagementService.SkillManagementServiceEndpoint.getAllCompetencyGroups(Pms.Data.Integration.SkillManagementService.getAllCompetencyGroupsRequest1 request) {
            return base.Channel.getAllCompetencyGroups(request);
        }
        
        public Pms.Data.Integration.SkillManagementService.GetAllCompetencyGroupsResponse getAllCompetencyGroups(Pms.Data.Integration.SkillManagementService.getAllCompetencyGroupsRequest arg0) {
            Pms.Data.Integration.SkillManagementService.getAllCompetencyGroupsRequest1 inValue = new Pms.Data.Integration.SkillManagementService.getAllCompetencyGroupsRequest1();
            inValue.arg0 = arg0;
            Pms.Data.Integration.SkillManagementService.getAllCompetencyGroupsResponse1 retVal = ((Pms.Data.Integration.SkillManagementService.SkillManagementServiceEndpoint)(this)).getAllCompetencyGroups(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Pms.Data.Integration.SkillManagementService.getAllTechnologyKnowledgeDetailsResponse1 Pms.Data.Integration.SkillManagementService.SkillManagementServiceEndpoint.getAllTechnologyKnowledgeDetails(Pms.Data.Integration.SkillManagementService.getAllTechnologyKnowledgeDetailsRequest1 request) {
            return base.Channel.getAllTechnologyKnowledgeDetails(request);
        }
        
        public Pms.Data.Integration.SkillManagementService.GetAllTechnologyKnowledgeDetailsResponse getAllTechnologyKnowledgeDetails(Pms.Data.Integration.SkillManagementService.getAllTechnologyKnowledgeDetailsRequest arg0) {
            Pms.Data.Integration.SkillManagementService.getAllTechnologyKnowledgeDetailsRequest1 inValue = new Pms.Data.Integration.SkillManagementService.getAllTechnologyKnowledgeDetailsRequest1();
            inValue.arg0 = arg0;
            Pms.Data.Integration.SkillManagementService.getAllTechnologyKnowledgeDetailsResponse1 retVal = ((Pms.Data.Integration.SkillManagementService.SkillManagementServiceEndpoint)(this)).getAllTechnologyKnowledgeDetails(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Pms.Data.Integration.SkillManagementService.getAllTechnologyKnowledgeGroupsResponse1 Pms.Data.Integration.SkillManagementService.SkillManagementServiceEndpoint.getAllTechnologyKnowledgeGroups(Pms.Data.Integration.SkillManagementService.getAllTechnologyKnowledgeGroupsRequest1 request) {
            return base.Channel.getAllTechnologyKnowledgeGroups(request);
        }
        
        public Pms.Data.Integration.SkillManagementService.GetAllTechnologyKnowledgeGroupsResponse getAllTechnologyKnowledgeGroups(Pms.Data.Integration.SkillManagementService.getAllTechnologyKnowledgeGroupsRequest arg0) {
            Pms.Data.Integration.SkillManagementService.getAllTechnologyKnowledgeGroupsRequest1 inValue = new Pms.Data.Integration.SkillManagementService.getAllTechnologyKnowledgeGroupsRequest1();
            inValue.arg0 = arg0;
            Pms.Data.Integration.SkillManagementService.getAllTechnologyKnowledgeGroupsResponse1 retVal = ((Pms.Data.Integration.SkillManagementService.SkillManagementServiceEndpoint)(this)).getAllTechnologyKnowledgeGroups(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Pms.Data.Integration.SkillManagementService.getScoreCardResponse1 Pms.Data.Integration.SkillManagementService.SkillManagementServiceEndpoint.getScoreCard(Pms.Data.Integration.SkillManagementService.getScoreCardRequest1 request) {
            return base.Channel.getScoreCard(request);
        }
        
        public Pms.Data.Integration.SkillManagementService.GetScoreCardResponse getScoreCard(Pms.Data.Integration.SkillManagementService.getScoreCardRequest arg0) {
            Pms.Data.Integration.SkillManagementService.getScoreCardRequest1 inValue = new Pms.Data.Integration.SkillManagementService.getScoreCardRequest1();
            inValue.arg0 = arg0;
            Pms.Data.Integration.SkillManagementService.getScoreCardResponse1 retVal = ((Pms.Data.Integration.SkillManagementService.SkillManagementServiceEndpoint)(this)).getScoreCard(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Pms.Data.Integration.SkillManagementService.saveScoreCardResponse1 Pms.Data.Integration.SkillManagementService.SkillManagementServiceEndpoint.saveScoreCard(Pms.Data.Integration.SkillManagementService.saveScoreCardRequest1 request) {
            return base.Channel.saveScoreCard(request);
        }
        
        public Pms.Data.Integration.SkillManagementService.SaveScoreCardResponse saveScoreCard(Pms.Data.Integration.SkillManagementService.saveScoreCardRequest arg0) {
            Pms.Data.Integration.SkillManagementService.saveScoreCardRequest1 inValue = new Pms.Data.Integration.SkillManagementService.saveScoreCardRequest1();
            inValue.arg0 = arg0;
            Pms.Data.Integration.SkillManagementService.saveScoreCardResponse1 retVal = ((Pms.Data.Integration.SkillManagementService.SkillManagementServiceEndpoint)(this)).saveScoreCard(inValue);
            return retVal.@return;
        }
    }
}
