//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.225
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "10.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Pms {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Pms() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Pms", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mm/dd/yy.
        /// </summary>
        internal static string DateFormat {
            get {
                return ResourceManager.GetString("DateFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Career path.
        /// </summary>
        internal static string Employee_CareerPathId {
            get {
                return ResourceManager.GetString("Employee_CareerPathId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Commision Pct.
        /// </summary>
        internal static string Employee_CommisionPct {
            get {
                return ResourceManager.GetString("Employee_CommisionPct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Competency.
        /// </summary>
        internal static string Employee_Competency {
            get {
                return ResourceManager.GetString("Employee_Competency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Competency group.
        /// </summary>
        internal static string Employee_CompetencyGroup {
            get {
                return ResourceManager.GetString("Employee_CompetencyGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Corp. location no..
        /// </summary>
        internal static string Employee_CorporateLocationNumber {
            get {
                return ResourceManager.GetString("Employee_CorporateLocationNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Department.
        /// </summary>
        internal static string Employee_Department {
            get {
                return ResourceManager.GetString("Employee_Department", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Corporate email.
        /// </summary>
        internal static string Employee_Email {
            get {
                return ResourceManager.GetString("Employee_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employee status.
        /// </summary>
        internal static string Employee_EmployeeStatus {
            get {
                return ResourceManager.GetString("Employee_EmployeeStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hired date.
        /// </summary>
        internal static string Employee_HireDate {
            get {
                return ResourceManager.GetString("Employee_HireDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manager.
        /// </summary>
        internal static string Employee_Manager {
            get {
                return ResourceManager.GetString("Employee_Manager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employee number.
        /// </summary>
        internal static string Employee_Number {
            get {
                return ResourceManager.GetString("Employee_Number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Office location.
        /// </summary>
        internal static string Employee_OfficeLocationId {
            get {
                return ResourceManager.GetString("Employee_OfficeLocationId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project manager.
        /// </summary>
        internal static string Employee_ProjectManager {
            get {
                return ResourceManager.GetString("Employee_ProjectManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Record status.
        /// </summary>
        internal static string Employee_RecordStatus {
            get {
                return ResourceManager.GetString("Employee_RecordStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Regional office headquarter.
        /// </summary>
        internal static string Employee_Rohq {
            get {
                return ResourceManager.GetString("Employee_Rohq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Salary.
        /// </summary>
        internal static string Employee_Salary {
            get {
                return ResourceManager.GetString("Employee_Salary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seat number.
        /// </summary>
        internal static string Employee_SeatNumber {
            get {
                return ResourceManager.GetString("Employee_SeatNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Staff Id.
        /// </summary>
        internal static string Employee_StaffId {
            get {
                return ResourceManager.GetString("Employee_StaffId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employee type.
        /// </summary>
        internal static string Employee_Type {
            get {
                return ResourceManager.GetString("Employee_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        internal static string General_Back {
            get {
                return ResourceManager.GetString("General_Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create.
        /// </summary>
        internal static string General_Create {
            get {
                return ResourceManager.GetString("General_Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string General_Delete {
            get {
                return ResourceManager.GetString("General_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detail.
        /// </summary>
        internal static string General_Detail {
            get {
                return ResourceManager.GetString("General_Detail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        internal static string General_Search {
            get {
                return ResourceManager.GetString("General_Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        internal static string General_Update {
            get {
                return ResourceManager.GetString("General_Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remember me?.
        /// </summary>
        internal static string LoginModel_RememberMe {
            get {
                return ResourceManager.GetString("LoginModel_RememberMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid username and/or password.
        /// </summary>
        internal static string Login_InvalidLogin {
            get {
                return ResourceManager.GetString("Login_InvalidLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account was successfully created.
        /// </summary>
        internal static string Notification_1_Detail {
            get {
                return ResourceManager.GetString("Notification_1_Detail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creation of account.
        /// </summary>
        internal static string Notification_1_Title {
            get {
                return ResourceManager.GetString("Notification_1_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account was successfully deleted.
        /// </summary>
        internal static string Notification_2_Detail {
            get {
                return ResourceManager.GetString("Notification_2_Detail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deletion of account.
        /// </summary>
        internal static string Notification_2_Title {
            get {
                return ResourceManager.GetString("Notification_2_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account was successfully updated.
        /// </summary>
        internal static string Notification_3_Detail {
            get {
                return ResourceManager.GetString("Notification_3_Detail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update of account.
        /// </summary>
        internal static string Notification_3_Title {
            get {
                return ResourceManager.GetString("Notification_3_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activation token field.
        /// </summary>
        internal static string Person_ActivationTokenField {
            get {
                return ResourceManager.GetString("Person_ActivationTokenField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        internal static string Person_Address {
            get {
                return ResourceManager.GetString("Person_Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Age.
        /// </summary>
        internal static string Person_Age {
            get {
                return ResourceManager.GetString("Person_Age", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Birthday.
        /// </summary>
        internal static string Person_Birthday {
            get {
                return ResourceManager.GetString("Person_Birthday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Birthday specified.
        /// </summary>
        internal static string Person_BirthdaySpecified {
            get {
                return ResourceManager.GetString("Person_BirthdaySpecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CivilStatus.
        /// </summary>
        internal static string Person_CivilStatus {
            get {
                return ResourceManager.GetString("Person_CivilStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country.
        /// </summary>
        internal static string Person_Country {
            get {
                return ResourceManager.GetString("Person_Country", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created by.
        /// </summary>
        internal static string Person_CreateBy {
            get {
                return ResourceManager.GetString("Person_CreateBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date created.
        /// </summary>
        internal static string Person_CreateDate {
            get {
                return ResourceManager.GetString("Person_CreateDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Personal email.
        /// </summary>
        internal static string Person_Email {
            get {
                return ResourceManager.GetString("Person_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First name.
        /// </summary>
        internal static string Person_FirstName {
            get {
                return ResourceManager.GetString("Person_FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full name.
        /// </summary>
        internal static string Person_FullName {
            get {
                return ResourceManager.GetString("Person_FullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home number.
        /// </summary>
        internal static string Person_HomeNumber {
            get {
                return ResourceManager.GetString("Person_HomeNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id.
        /// </summary>
        internal static string Person_Id {
            get {
                return ResourceManager.GetString("Person_Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last name.
        /// </summary>
        internal static string Person_LastName {
            get {
                return ResourceManager.GetString("Person_LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Middle name.
        /// </summary>
        internal static string Person_MiddleName {
            get {
                return ResourceManager.GetString("Person_MiddleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passport expiry.
        /// </summary>
        internal static string Person_PassportExpiry {
            get {
                return ResourceManager.GetString("Person_PassportExpiry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passport number.
        /// </summary>
        internal static string Person_PassportNumber {
            get {
                return ResourceManager.GetString("Person_PassportNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        internal static string Person_Password {
            get {
                return ResourceManager.GetString("Person_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        internal static string Person_PersonStatus {
            get {
                return ResourceManager.GetString("Person_PersonStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        internal static string Person_PersonType {
            get {
                return ResourceManager.GetString("Person_PersonType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Primary number.
        /// </summary>
        internal static string Person_PrimaryNumber {
            get {
                return ResourceManager.GetString("Person_PrimaryNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reason.
        /// </summary>
        internal static string Person_Reason {
            get {
                return ResourceManager.GetString("Person_Reason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Record status.
        /// </summary>
        internal static string Person_RecordStatus {
            get {
                return ResourceManager.GetString("Person_RecordStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Secondary number.
        /// </summary>
        internal static string Person_SecondaryNumber {
            get {
                return ResourceManager.GetString("Person_SecondaryNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sex.
        /// </summary>
        internal static string Person_Sex {
            get {
                return ResourceManager.GetString("Person_Sex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Social sec. #.
        /// </summary>
        internal static string Person_SocialSecurityNumber {
            get {
                return ResourceManager.GetString("Person_SocialSecurityNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change by.
        /// </summary>
        internal static string Person_StatusChangeBy {
            get {
                return ResourceManager.GetString("Person_StatusChangeBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status change reason.
        /// </summary>
        internal static string Person_StatusChangeReason {
            get {
                return ResourceManager.GetString("Person_StatusChangeReason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status change time.
        /// </summary>
        internal static string Person_StatusChangeTime {
            get {
                return ResourceManager.GetString("Person_StatusChangeTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updated by.
        /// </summary>
        internal static string Person_UpdateBy {
            get {
                return ResourceManager.GetString("Person_UpdateBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date updated.
        /// </summary>
        internal static string Person_UpdateDate {
            get {
                return ResourceManager.GetString("Person_UpdateDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upate reason.
        /// </summary>
        internal static string Person_UpdateReason {
            get {
                return ResourceManager.GetString("Person_UpdateReason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        internal static string Person_Username {
            get {
                return ResourceManager.GetString("Person_Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Years experience in IT.
        /// </summary>
        internal static string Person_YearsItExperience {
            get {
                return ResourceManager.GetString("Person_YearsItExperience", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date must be in &quot;mm/dd/yyyy&quot;.
        /// </summary>
        internal static string Validation_Date {
            get {
                return ResourceManager.GetString("Validation_Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome.
        /// </summary>
        internal static string Welcome {
            get {
                return ResourceManager.GetString("Welcome", resourceCulture);
            }
        }
    }
}
